<a href="https://colab.research.google.com/github/sonenhur/k5_python/blob/main/Numpy%EC%97%B0%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
x = np.arange(1,10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
x.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
x=np.array([1,2,3])
x

array([1, 2, 3])

In [6]:
x.reshape((1,3))

array([[1, 2, 3]])

In [8]:
x[np.newaxis,:]
x

array([1, 2, 3])

In [9]:
x.reshape((3,1))

array([[1],
       [2],
       [3]])

In [10]:
x=np.array([1,2,3])
y=np.array([3,2,1])
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [11]:
z=[99,99,99]

In [12]:
type(x)

numpy.ndarray

In [13]:
type(z)

list

In [14]:
np.concatenate([x,y,z])

array([ 1,  2,  3,  3,  2,  1, 99, 99, 99])

In [16]:
grid=np.array([1,2,3,4,5,6])

In [17]:
grid.reshape((2,3))

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
grid

array([1, 2, 3, 4, 5, 6])

In [19]:
np.concatenate([grid,grid])

array([1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6])

In [26]:
grid2= np.array([[1,2,3],[4,5,6]])
grid2

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
np.concatenate([grid2, grid2], axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [31]:
x=np.array([1,2,3])
grid=np.array([[9,8,7],[6,5,4]])
grid

array([[9, 8, 7],
       [6, 5, 4]])

In [33]:
np.vstack([x,grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])