<a href="https://colab.research.google.com/github/sonenhur/k5_python/blob/main/Numpy%EC%97%B0%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
x = np.arange(1,10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
x.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
x=np.array([1,2,3])
x

array([1, 2, 3])

In [6]:
x.reshape((1,3))

array([[1, 2, 3]])

In [8]:
x[np.newaxis,:]
x

array([1, 2, 3])

In [9]:
x.reshape((3,1))

array([[1],
       [2],
       [3]])

In [10]:
x=np.array([1,2,3])
y=np.array([3,2,1])
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [11]:
z=[99,99,99]

In [12]:
type(x)

numpy.ndarray

In [13]:
type(z)

list

In [14]:
np.concatenate([x,y,z])

array([ 1,  2,  3,  3,  2,  1, 99, 99, 99])

In [16]:
grid=np.array([1,2,3,4,5,6])

In [17]:
grid.reshape((2,3))

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
grid

array([1, 2, 3, 4, 5, 6])

In [19]:
np.concatenate([grid,grid])

array([1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6])

In [26]:
grid2= np.array([[1,2,3],[4,5,6]])
grid2

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
np.concatenate([grid2, grid2], axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [31]:
x=np.array([1,2,3])
grid=np.array([[9,8,7],[6,5,4]])
grid

array([[9, 8, 7],
       [6, 5, 4]])

In [33]:
np.vstack([x,grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [44]:
y=np.array([[99],[99]])
y

array([[99],
       [99]])

In [46]:
np.hstack([grid,y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [47]:
x=[1,2,3,99,99,3,2,1]
x1,x2,x3=np.split(x,[3,5])

In [52]:
x1

array([3, 2, 1])

In [53]:
x2

array([99, 99])

In [54]:
x3

array([3, 2, 1])

In [56]:
x=np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [58]:
grid = x.reshape(4,4)
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [59]:
upper,lower=np.split(grid,[2])

In [60]:
upper

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [61]:
lower

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [63]:
left,right = np.hsplit(grid,[2])

In [64]:
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [65]:
right

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [73]:
np.random.seed(0)
def compute_reciprocals(values):
    output=np.empty(len(values))
    for i in range(len(values)):
        output[i]=1.0/values[i]
        return output
values = np.random.randint(1,10,size=5)
compute_reciprocals(values)

array([1.66666667e-001, 0.00000000e+000, 2.52175196e+180, 5.55979303e+141,
       3.16202013e-322])

In [74]:
big_array=np.random.randint(1,100,size=1000000)
%timeit compute_reciprocals(big_array)

4.01 µs ± 1.05 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [75]:
pip install line_profiler

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 714.8/714.8 kB 8.2 MB/s eta 0:00:00


In [76]:
!pip install profiler

In [77]:
%load_ext line_profiler

In [79]:
%lprun -f compute_reciprocals compute_reciprocals(big_array)

In [80]:
compute_reciprocals(values)

array([1.66666667e-001, 4.94065646e-324, 1.97626258e-323, 1.97626258e-323,
       3.95252517e-323])

In [81]:
print(1.0/values)

[0.16666667 1.         0.25       0.25       0.125     ]


In [88]:
values = [4,6,3,5,8]
compute_reciprocals(values)

array([0.25 , 1.   , 0.25 , 0.25 , 0.125])

In [90]:
x = np.arange(9)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [91]:
x = x.reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [93]:
%timeit (2**x)
2**x

2.99 µs ± 940 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])

In [94]:
x=np.arange(5)
y=np.empty(5)
y

array([0.25 , 1.   , 0.25 , 0.25 , 0.125])

In [95]:
np.multiply(x,10,out=y)

array([ 0., 10., 20., 30., 40.])

In [98]:
y
y=np.zeros(10)
y

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [100]:
np.power(2,x,out=y[::2])
y

array([ 1.,  0.,  2.,  0.,  4.,  0.,  8.,  0., 16.,  0.])

In [101]:
x=np.arange(1,6)
x

array([1, 2, 3, 4, 5])

In [102]:
np.add.reduce(x)

15

In [103]:
np.multiply.reduce(x)

120

In [105]:
big_array=np.random.rand(1000000)
%timeit sum(big_array)

118 ms ± 36.6 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [106]:
%timeit np.sum(big_array)

377 µs ± 22.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [109]:
M=np.random.random((3,4))
M

array([[0.95082415, 0.85373438, 0.72268951, 0.96553886],
       [0.87515745, 0.03152619, 0.68217504, 0.71101428],
       [0.06525869, 0.48899158, 0.74344374, 0.99222836]])

In [110]:
M.sum()

8.082582216732394

In [111]:
M.sum(axis=0)

array([1.89124029, 1.37425215, 2.14830828, 2.66878149])

In [112]:
M.sum(axis=1)

array([3.4927869 , 2.29987296, 2.28992236])

In [114]:
x=np.arange(12)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [116]:
x = x.reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [117]:
x.sum()

66

In [118]:
x.sum(axis=0)

array([12, 15, 18, 21])

In [119]:
x.sum(axis=1)

array([ 6, 22, 38])